source 'https://rubygems.org'

gem 'foreman'
gem 'guard'
gem 'guard-livereload'
gem 'guard-sass'
gem 'guard-shell'

# gem 'wordless'
# gem 'wordless_gem'
# gem 'wordmove'

gem 'capistrano-git-submodule-strategy'
gem 'capistrano', github: 'peterhoeg/capistrano', branch: 'nixos'
gem 'capistrano-wp-deploy', github: 'peterhoeg/wp-deploy', branch: 'v2-branch'
#gem 'capistrano-wp-deploy', github: 'Mixd/wp-deploy', branch: 'v2-branch'
#gem 'capistrano-wp-deploy', path: '~/src/active/wp-deploy'

# these are needed for EC
gem 'net-ssh', '>= 4.0.0.beta3'
gem 'ed25519'
gem 'rbnacl-libsodium'
gem 'bcrypt_pbkdf'
